# Generated by Django 4.0.1 on 2022-01-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('molt', models.IntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('added', models.DateField(auto_now=True)),
            ],
        ),
    ]
