# Generated by Django 4.0.1 on 2022-01-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('spiders', '0003_animalslist_spider_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalslist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
