# Generated by Django 4.0.1 on 2022-01-29 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0004_alter_animalslist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='added',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
