# Generated by Django 4.0.1 on 2022-01-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0005_alter_spider_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spider',
            old_name='added',
            new_name='joined',
        ),
    ]
