# Generated by Django 4.0.1 on 2022-01-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('spiders', '0006_rename_added_spider_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='list',
        ),
        migrations.AddField(
            model_name='spider',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.DeleteModel(
            name='AnimalsList',
        ),
    ]
