# Generated by Django 4.0.1 on 2022-01-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0008_alter_spider_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not sure')], max_length=1, null=True),
        ),
    ]
