# Generated by Django 4.0.1 on 2022-01-30 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0010_alter_spider_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='molt',
        ),
        migrations.CreateModel(
            name='Molt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('number', models.IntegerField()),
                ('spider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spiders.spider')),
            ],
        ),
    ]
