# Generated by Django 4.0.1 on 2022-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0011_remove_spider_molt_molt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molt',
            options={'ordering': ('spider', '-date')},
        ),
        migrations.AddField(
            model_name='spider',
            name='current_molt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
