# Generated by Django 4.0.1 on 2022-02-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0013_alter_molt_options_spider_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Not sure')], default='F', max_length=1, null=True),
        ),
    ]
