# Generated by Django 4.0.1 on 2022-02-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0014_alter_spider_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molt',
            options={'ordering': ['spider', '-number', '-date']},
        ),
    ]
