# Generated by Django 4.0.1 on 2022-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0015_alter_molt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='photo',
            field=models.ImageField(blank=True, default='t-default.jpg', null=True, upload_to=''),
        ),
    ]
