# Generated by Django 4.0.1 on 2023-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0016_spider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='photo',
            field=models.ImageField(default='t-default.jpg', upload_to=''),
        ),
    ]
